server:
  port: 80
  servlet:
    context-path: /community
spring:
  main:
    allow-bean-definition-overriding: true
  data:
    elasticsearch:
      cluster-name: nowcoder
      cluster-nodes: 127.0.0.1:9300
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: community-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000
  mail:
    host: smtp.163.com
    username: wonderccc@163.com
#
    password: FMBIQCBWEVEDKGWW
    protocol: smtps
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 3000
#      RedisProperties
  redis:
    database: 11
    host: localhost
    port: 6379
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hongna.community.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
#community
community:
  path:
    domain: http://localhost:80
#    头像保存位置
    upload: d:/work/data/upload



